language: dart
sudo: required
addons:
  chrome: stable
matrix:
  include:
    - dart: dev
      script:
        - dartanalyzer --fatal-infos --fatal-lints --fatal-warnings lib/ test/
    - dart: dev
      script:
        - dartfmt --set-exit-if-changed -l 120 -n .
    - dart: dev
      dart_task:
        test: --platform firefox -j 1
    - dart: dev
      script:
        - pub run build_runner test -- --platform chrome
    #TODO: does not work
#    - dart: dev
#      script:
#        - pub run dart_dev coverage
#        - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]
cache:
  directories:
    - $HOME/.pub-cache
