name: sentry_client
version: 4.0.4
description: The Dart library for sending data to the Sentry server.
authors:
  - Ivan Evsikov <ivan.evsikov@team.wrike.com>
homepage: https://github.com/wrike/sentry_client
environment:
  sdk: '>=1.21.1 <2.0.0'

dependencies:
  uuid: ^0.5.0

dev_dependencies:
  test: ^0.12.15
  coverage: '>=0.7.9 < 1.0.0'
  mockito: ^2.0.0
  quiver: '>=0.21.4 < 1.0.0'
  dart_dev: ^1.7.2
  dart_style: ^1.0.7
  build_runner: ^0.7.9
  build_test: ^0.10.0

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart

