name: sentry_client
version: 4.1.1
description: The Dart library for sending data to the Sentry server.
authors:
  - Ivan Evsikov <ivan.evsikov@team.wrike.com>
homepage: https://github.com/wrike/sentry_client
environment:
  sdk: '>=1.21.1 <3.0.0'

dependencies:
  uuid: ^0.5.0

dev_dependencies:
  test: '>=0.12.15 <2.0.0'
  coverage: '>=0.7.9 <2.0.0'
  mockito: ^3.0.0
  quiver: '>=0.21.4 <2.0.0'
  dart_dev: '>=1.7.2'
  #dart_style: ^1.0.7

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart

